name: Ping
on:
  push:
    branches:
      - 'main'

env:
  PROJECT: protocloud-368418
  IMAGE_NAME: ping

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and Push
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ${{ env.PROJECT }}/${{ env.IMAGE_NAME }}
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GOOGLE_CREDENTIALS }}
          tags: latest


      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - uses: hashicorp/setup-terraform@v2

      - run: terraform init

      - run: terraform plan -no-color

      - run: terraform apply -auto-approve
